//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLibrarySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public System.DateTime PickupDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> IsDone { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Book Book { get; set; }
    }
}
